version: '2'
services:
    redis:
        hostname: redis
        image: redis:latest
        ports:
          - "6379:6379"
        restart: always

    worker:
#        image: waterlp-pywr:latest
        build: .
        env_file: variables.env
        command: [celery, worker, --app=waterlp.app, --concurrency=10, --loglevel=WARNING]
        volumes:
            - .:/app
            - /etc/localtime:/etc/localtime
#        links:
#            - redis
        network_mode: host
        depends_on:
            - redis