version: '3'
services:

    redis:
#        hostname: waterlp-redis
        image: redis:latest
        ports:
          - "6379:6379"
        network_mode: "host"
        restart: always

    worker:
#        image: waterlp-pywr:latest
        build: .
        env_file: variables.env
        command: [celery, worker, --app=waterlp.app, --concurrency=4, --loglevel=WARNING]
        volumes:
            - .:/app
            - /etc/localtime:/etc/localtime
#        links:
#            - waterlp-redis:redis
        network_mode: "host"
        depends_on:
            - redis