version: '2'
services:
    redis:
        hostname: redis
        image: redis:latest
        ports:
          - "6379:6379"
        restart: always

    worker:
        build: .
        command: [celery, worker, --concurrency=10, --loglevel=WARNING]
        volumes:
            - .:/app
        links:
            - redis
        depends_on:
            - redis